### ISSUE TITLE
What should be configurable?

### ISSUE THREAD

**Issue by interrogator** [bitpanda-labs/loggo#71]
Right now it seems like some things should be configurable and are not; other things do need need to be and are.

* minimum alert level could be configurable
* Users might like to be able to pass in custom strings for autologging

Meanwhile:

* will anybody care about `max_dict_depth` or the string with which private data is obscured?

Just something to think about.

**Comment by interrogator** [comment]
@hukkinj1 do you wanna take one last look at the init and tell me if you want to change anything either way, i.e. making it configurable or making it not? 

i think that we could consider removing `max_dict_depth`, `obscured` str customisation and `raise_logging_errors` (and making logging errors raise, now that things are v stable)

We should be able to get this closed

**Comment by hukkinj1** [comment]
I'd be happy to see `max_dict_depth`, `obscured` and `error_level` (just use the same level for exceptions as any other log) gone. I wouldn't want to remove `raise_logging_errors` as I don't have full knowledge on if logging can fail e.g. when using custom handlers like the graylog one. If logging breaks due to graylog network error or similar, we prefer system running with no logs rather than system crashing with no logs.

**Comment by hukkinj1** [comment]
As a response to the suggestion of adding minimum alert level as configurable: so far haven't had the need for it, so I don't support adding it unless needed. Doing that easily leads us to current state, where we want to remove unneeded configurables. Adding stuff is always easier than removing, due to it not being a breaking change.

**Comment by interrogator** [comment]
OK. Then whoever has the time, please go forth and change `max_dict_depth` and `obscured` into globals in capital letters near the top of `loggo/loggo.py`... Error level stuff can and should probably be a different PR.

**Comment by hukkinj1** [comment]
Done in https://github.com/bitpanda-labs/loggo/pull/101
